# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmt', '0002_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='project',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='question',
            name='project_id',
            field=models.CharField(default='', max_length=12),
        ),
    ]
